version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-log-samarizer
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    # Uncomment the following lines if you need to expose more ports
    # ports:
    #   - "8000:8000"
    
    # Uncomment and modify the following if you need to add environment variables
    # environment:
    #   - ENV_VAR_NAME=value
    
    # Uncomment the following if you need to add a command that overrides the Dockerfile CMD
    # command: python your_script.py
    
    # Uncomment the following if you need to add more services (like a database)
    # depends_on:
    #   - db
    #   - redis

# Uncomment and configure additional services as needed
# services:
#   db:
#     image: postgres:13
#     environment:
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=chat_logs
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     ports:
#       - "5432:5432"
# 
#   redis:
#     image: redis:alpine
#     ports:
#       - "6379:6379"
# 
# volumes:
#   postgres_data:
